SQLALCHEMY_DATABASE_URL = "sqlite:///./sql_app.db"
GENERATED_DATA_DIR = 'data'

USER_DATA_FILE_NAME = 'users.csv'
DIGITAL_PRODUCT_DATA_FILE_NAME = 'digital_products.csv'
PHYSICAL_PRODUCT_DATA_FILE_NAME = 'physical_products.csv'
STORE_DATA_FILE_NAME = 'stores.csv'
ADDRESS_DATA_FILE_NAME = 'addresses.csv'
STORES_PHYSICAL_PRODUCTS_DATA_FILE_NAME = 'stores_physical_products.csv'

USER_DATA_ROWS_NUMBER = 1000
DIGITAL_PRODUCT_DATA_ROWS_NUMBER = 100
PHYSICAL_PRODUCT_DATA_ROWS_NUMBER = 100
STORE_DATA_ROWS_NUMBER = 50
ADDRESS_DATA_ROWS_NUMBER = 50
STORES_PHYSICAL_PRODUCTS_DATA_ROWS_NUMBER = 200
